# Generated by Django 2.2.12 on 2020-08-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t1',
            options={'managed': True},
        ),
    ]
